service: db-writer
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 8881
functions:
  fn:
    handler: src/index.handler
    events:
      - http: POST /historical
      - http: POST /real-time
